CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CLOCK_CONTROL=y

CONFIG_LVGL=y
CONFIG_LVGL_HOR_RES_MAX=240
CONFIG_LVGL_VER_RES_MAX=240
CONFIG_LVGL_USE_TIMER=y
CONFIG_LVGL_USE_LABEL=y
CONFIG_LVGL_USE_BAR=y
CONFIG_LVGL_USE_LINE=y
CONFIG_LVGL_COLOR_DEPTH_16=y

CONFIG_SENSOR=y
CONFIG_BMI270=y
CONFIG_BMP581=y

CONFIG_ZSWATCH_ROUND_SCREEN=y
CONFIG_SEGMENT34_SHOW_LUNAR=y