CONFIG_LVGL=y
CONFIG_LV_Z_FLUSH_THREAD=y
CONFIG_LV_Z_FLUSH_THREAD_PRIORITY=0
CONFIG_LV_Z_DOUBLE_VBUF=y
CONFIG_LV_Z_DRAW_BUF_SIZE=8192
CONFIG_LV_Z_HOR_RES_MAX=240
CONFIG_LV_Z_VER_RES_MAX=240
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BAR=y
CONFIG_LV_USE_LINE=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_CONTAINER=y
CONFIG_LV_USE_BUTTON=y
CONFIG_LV_USE_FONT_MONTSERRAT_10=y
CONFIG_LV_USE_FONT_MONTSERRAT_12=y
CONFIG_LV_USE_FONT_MONTSERRAT_14=y
CONFIG_LV_USE_FONT_MONTSERRAT_16=y
CONFIG_LV_USE_FONT_MONTSERRAT_20=y
CONFIG_LV_USE_FONT_MONTSERRAT_24=y
CONFIG_LV_USE_FONT_MONTSERRAT_32=y

CONFIG_TIME=y
CONFIG_DATE_TIME=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=INF

CONFIG_SEGMENT34_LANG_EN=y
CONFIG_SEGMENT34_LANG_ZH=y
CONFIG_SEGMENT34_DEFAULT_LANG="zh"
CONFIG_SEGMENT34_SHOW_LUNAR=y
CONFIG_SEGMENT34_SHOW_WEATHER=y
CONFIG_SEGMENT34_SHOW_SECONDS=y

CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_DISPLAY=y
CONFIG_GC9A01=y

CONFIG_I2C=y
CONFIG_SPI=y